### ISSUE TITLE
how to use this project!

### ISSUE THREAD

**Issue by rosliwanlei** [Jbwasse2/topological-mapping#9]
is this project use for ros1? and it can make topological map when robot moving ?

**Comment by Jbwasse2** [comment]
Overall this project has not been developed enough for anyone in the ROS community to use it without putting in a significant amount of work that I will be doing anyways. In like a few months it should be ready for anyone in the ROS community to use. 
I do not plan on supporting ROS1, only ROS2. It might be capable of building a topological map online, I will have to do some benchmarking before I can say for certain (and of course this depends on your hardware). My previous work built the maps offline.

**Comment by rosliwanlei** [comment]
thanks for you reply ! do you have any suggest about build topology map when robot moving ? or other open source code about this ? i want to make a topology online ,then i can navigation based the map. do you have any suggestions? thank you !

**Comment by Jbwasse2** [comment]
There are a few issues with building topological maps that are important to recognize. In my recently submitted research I found that if you have visual similarities in the environment, the topological map may create an erroneous edge between the nodes which I call "wormholes". Examples of wormholes in a topological map can be seen in the following images
![wall](https://user-images.githubusercontent.com/17070462/118490885-10778880-b6e4-11eb-9695-cdf135469a26.png).
![room](https://user-images.githubusercontent.com/17070462/118491769-f12d2b00-b6e4-11eb-890f-2ef5d0d10fa1.png)
 It shouldn't be surprising that the topological map thinks that the top two images are visually similar since they are images of a wall. The bottom two images I believe are labeled as visually similar due to the camera perspective and geometry of the environment. These wormholes cause problems when the robot tries planning over the map.

Also it should be noted that recent works in topological mapping use a deep learning model to determine how "similar" two nodes are. These models typically require a GPU whereas state of the art metric mapping algorithms work fine with just a CPU.

There is likely more problems that will have to be solved before topological mapping will work on a real world robot. Such as acquiring data for your deep learning models as well as distribution shift if you use simulator data. However, I haven't done enough research where I can say for certain how big of an issue these will be.

I am not aware of any topological mapping papers that make the map online that have also had their code run on a real world robot and be open source. The only open sourced topological mapping work besides mine that I know off of the top of my head [is this work](https://github.com/xymeng/rmp_nav/tree/master/topological_nav), but just like my work they build the map offline.
